/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Percy
 */
public class FrmMenuPrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipalAdmin
     */
    public FrmMenuPrincipalAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgAdministrador = new javax.swing.JLabel();
        imgPerfiles = new javax.swing.JLabel();
        imgNuevaReservacion = new javax.swing.JLabel();
        imgReservaciones = new javax.swing.JLabel();
        btnAdministrador = new javax.swing.JButton();
        btnPerfiles = new javax.swing.JButton();
        btnNuevaReservacion = new javax.swing.JButton();
        btnReservaciones = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        txtUsuarioActivo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgAdministrador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(imgAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 190, 190));

        imgPerfiles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(imgPerfiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 190, 190));

        imgNuevaReservacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(imgNuevaReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 190, 190));

        imgReservaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(imgReservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 190, 190));

        btnAdministrador.setText("Administrador");
        jPanel1.add(btnAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 190, 50));

        btnPerfiles.setText("Perfiles");
        jPanel1.add(btnPerfiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 190, 50));

        btnNuevaReservacion.setText("Nueva Reservacion");
        jPanel1.add(btnNuevaReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 190, 50));

        btnReservaciones.setText("Reservaciones");
        jPanel1.add(btnReservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 190, 50));

        btnAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("jButton5");
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 110, 120));

        txtUsuarioActivo.setText("Bienvenido Admin");
        jPanel1.add(txtUsuarioActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 360, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdministrador;
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnNuevaReservacion;
    public javax.swing.JButton btnPerfiles;
    public javax.swing.JButton btnReservaciones;
    public javax.swing.JLabel imgAdministrador;
    public javax.swing.JLabel imgNuevaReservacion;
    public javax.swing.JLabel imgPerfiles;
    public javax.swing.JLabel imgReservaciones;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel txtUsuarioActivo;
    // End of variables declaration//GEN-END:variables
}
